### ISSUE TITLE
程序“redissyncer-cli”无法运行: 没有应用程序与此操作的指定文件有关联。

### ISSUE THREAD

**Issue by incubus-ohy** [TraceNature/redissyncer-cli#1]
您好，请问这个是否支持windows10运行
![image](https://user-images.githubusercontent.com/40196468/119777594-f9f9da00-bef8-11eb-8a36-05642026f5f2.png)
后续是否会考虑做个web端的页面便于交互

**Comment by pingxingshikong** [comment]
https://github.com/TraceNature/redissyncer 
直接docker-compose拉起来有web界面

**Comment by jiashiwen** [comment]
请下载对应操作系统release版本，或自行在相关os编译。
https://github.com/TraceNature/redissyncer-cli/releases/download/v0.1.0/redissyncer-cli-0.1.0-windows-amd64.zip
